# Generated by Django 4.2.1 on 2023-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vid_stream_violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viol_date', models.DateField()),
                ('viol_time', models.TimeField()),
                ('violations', models.CharField(max_length=100)),
                ('viol_suit', models.IntegerField()),
                ('viol_without_suit', models.IntegerField()),
                ('viol_Camera_id', models.IntegerField()),
                ('idd', models.IntegerField()),
            ],
        ),
    ]
