# Generated by Django 4.2.1 on 2023-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_violation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_stream_cameras',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField()),
                ('password', models.CharField()),
                ('ip', models.CharField()),
                ('cam_location', models.CharField()),
                ('Model_no', models.CharField()),
                ('Serial_no', models.CharField()),
                ('Port', models.CharField()),
                ('analytics', models.BooleanField()),
                ('video', models.BooleanField()),
                ('localhost', models.CharField()),
            ],
        ),
    ]
