# Generated by Django 4.2.1 on 2023-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_violation', '0002_vid_stream_cameras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vid_stream_violations',
            old_name='viol_Camera_id',
            new_name='viol_camera_id',
        ),
    ]
