# Generated by Django 4.2.1 on 2023-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_violation', '0003_rename_viol_camera_id_vid_stream_violations_viol_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid_stream_cameras',
            name='camera',
            field=models.IntegerField(),
        ),
    ]
