# Generated by Django 4.2.1 on 2023-05-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_violation', '0004_alter_vid_stream_cameras_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid_stream_cameras',
            name='camera',
            field=models.CharField(),
        ),
    ]
