# Generated by Django 4.2.1 on 2023-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_violation', '0006_alter_vid_stream_violations_viol_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid_stream_violations',
            name='viol_camera_id',
            field=models.IntegerField(),
        ),
    ]
